version: '3'

services:
  api:
    container_name: urs-api-dev
    build:
      context: ./api/
      args:
        - DEPLOY_ENV=dev
    ports:
      - "8000:8000"
    env_file:
      - ./env/dev/api.dev.env
    depends_on:
      - db
    command: [ "./entrypoint.sh" ]
  db:
    image: 'postgres:15'
    container_name: postgres-dev
    volumes:
      - ./_docker/pgsql:/var/lib/postgres/data/
    env_file:
      - ./env/dev/postgres.dev.env
  pgadmin:
    container_name: pgadmin-dev
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
  rabbitmq:
    image: rabbitmq:3.12.0-management
    container_name: rabbitmq-dev
    ports:
      - "5672:5672"
      - "15672:15672"
  client:
    container_name: urs-client-dev
    build:
      context: ./client/
      args:
        - DEPLOY_ENV=dev
    ports:
      - "3000:3000"
    env_file:
      - ./env/dev/client.dev.env
    command: [ "/app/entrypoint.sh" ]