services:
  api:
    image: university-rating-system-api:latest
    container_name: urs-api-prod
    build:
      context: ./api/
      args:
        - DEPLOY_ENV=prod
        - APP_USER_UID=1000
    ports:
      - "8000:8000"
    env_file:
      - ./env/prod/api.prod.env
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    container_name: postgres-prod
    volumes:
      - pg_data:/var/lib/postgres/data/
    env_file:
      - ./env/prod/postgres.prod.env

volumes:
  pg_data: