services:
  web:
    image: web-prod-i
    container_name: web-prod-c
    build:
      context: ./src/
      args:
        - DEPLOY_ENV=prod
        - APP_USER_UID=1000
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app/src/
    env_file:
      - ./env/prod/web.prod.env
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    container_name: postgres-prod-c
    volumes:
      - pg_data:/var/lib/postgres/data/
    env_file:
      - ./env/prod/postgres.prod.env

volumes:
  pg_data: