services:
  api:
    image: university-rating-system-api:latest
    container_name: urs-api-dev
    build:
      context: ./api/
      args:
        - DEPLOY_ENV=dev
        - APP_USER_UID=1000
    ports:
      - "8000:8000"
    volumes:
      - ./api/:/app/src/
    env_file:
      - ./env/dev/api.dev.env
    depends_on:
      - db
  db:
    image: postgres:15.2-alpine
    container_name: postgres-dev
    volumes:
      - pg_data:/var/lib/postgres/data/
    env_file:
      - ./env/dev/postgres.dev.env

volumes:
  pg_data: